### ISSUE TITLE
Nonpareil crashes when called in /usr/local/bin

### ISSUE THREAD

**Issue by wjg57** [brouhaha/nonpareil#7]
After installation

$ cd /usr/local/bin
$ nonpareil /usr/local/lib/nonpareil/35.nui

results in:

XML error: Start tag expected, '<' not found
Segmentation fault (core dumped)

Works fine when called outside /usr/local/bin.

**Comment by brouhaha** [comment]
That's strange. I just tested it on my development machine (Fedora 38), using those commands, except that I had to put "./" ahead of nonpareil, and it ran fine. Is it possible that your PATH includes a different nonpareil executable somewhere?

**Comment by brouhaha** [comment]
Since I can't reproduce the problem I can't fix it. Closing.
